---
- name: Update programs
  become: true
  ansible.builtin.shell: snap refresh
- name: Install programs
  become: true
  community.general.snap:
    classic: yes
    name: "{{ item }}" 
  loop: "{{ programs }}"