---
- name: Ensure docker group exists
  become: true
  group:
    name: docker
    state: present

- name: Add docker users to the docker group
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
