---
# defaults file for oh-my-zsh-plugins
folder: /home/{{ user }}/.oh-my-zsh/custom/plugins
plugins:
- name: zsh-syntax-highlighting
  url: https://github.com/zsh-users/zsh-syntax-highlighting.git
- name: zsh-autosuggestions
  url: https://github.com/zsh-users/zsh-autosuggestions.git
- name: zsh-completions
  url: https://github.com/zsh-users/zsh-completions.git

spaceship: 
  enabled: true
  folder: /home/{{ user }}/.oh-my-zsh/themes/spaceship-prompt
  url: https://github.com/spaceship-prompt/spaceship-prompt.git