---
collections:
  - name: community.general

roles:
  - name: comcast.sdkman
  - name: grzegorznowak.nvm_node
  - name: gantsign.antigen
  - name: geerlingguy.docker
  - name: webarchitect609.jet_brains_toolbox