---
- hosts: localhost
  vars:
    docker_users:
    - dakon
    sdkman_user: dakon
    sdkman_group: dakon
  roles:
    - common
    - google-chrome
    - snap
    - snap-dev
    - vscode-extensions
    - docker-compose
    - docker-users
    - sdkman