---
- hosts: localhost
  vars:
    user: dakon
    docker_users:
    - "{{ user }}"
  roles:
    - common
    - google-chrome
    - snap
    - snap-dev
    - vscode-extensions
    - docker-compose
    - docker-users
    - role: comcast.sdkman
      sdkman_user: "{{ user }}"
      sdkman_group: "{{ user }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 11.0.12-open }
        - { candidate: maven, version: 3.8.4 }
      sdkman_defaults:
        java: 11.0.12-open
        maven: 3.8.4
    - role: grzegorznowak.nvm_node
      become: true
      nvm_node_version: "16.13.1"
    - role: gantsign.oh-my-zsh
      users:
      - username: "{{ user }}"
        oh_my_zsh:
          theme: robbyrussell
          plugins:
            - git
            - nvm
            - node
            - sdk
            - docker
            - docker-compose