---
- hosts: localhost
  vars:
    user: dakon
  roles:
    - common
    - google-chrome
    - snap
    - snap-dev
    - vscode-extensions
    - role: geerlingguy.docker
      become: true
      docker_users:
      - "{{ user }}"
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
              - nvm
              - docker
              - command-not-found
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - zsh-completions
    - oh-my-zsh-plugins
    - role: comcast.sdkman
      sdkman_user: "{{ user }}"
      sdkman_group: "{{ user }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 11.0.12-open }
        - { candidate: maven, version: 3.8.4 }
      sdkman_defaults:
        java: 11.0.12-open
        maven: 3.8.4
    - nvm-node