---
- hosts: localhost
  vars:
    user: damico
    base:
    - htop
    - build-essential
    - net-tools
    - git
    - gitg
    - libfuse2
    programs:
    - code
    programs_dev:
    - termius-app
    vscode_extensions:
    - vscode-icons-team.vscode-icons
    - ms-azuretools.vscode-docker
    - redhat.ansible
  roles:
    - common
    - google-chrome
    - snap
    - snap-dev
    - common-folder
    - vscode-extensions
    - role: geerlingguy.docker
      become: true
      docker_users:
        - "{{ user }}"
    - role: gantsign.antigen
      users:
        - username: "{{ user }}"
          antigen_libraries:
            - name: oh-my-zsh
          antigen_theme:
            name: robbyrussell
          antigen_bundles:
            - name: git
            - name: docker
            - name: command-not-found
            - name: zsh-syntax-highlighting
              url: zsh-users/zsh-syntax-highlighting
            - name: zsh-autosuggestions
              url: zsh-users/zsh-autosuggestions
            - name: zsh-completions
              url: zsh-users/zsh-completions
    - role: webarchitect609.jet_brains_toolbox
      become: true
      toolbox_version: "1.26.2.13244"
      toolbox_install_dir: "/home/{{ user }}/work/programs"
      toolbox_install_for_user: "{{ user }}"
    - role: comcast.sdkman
      sdkman_user: "{{ user }}"
      sdkman_group: "{{ user }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 11.0.12-open }
        - { candidate: maven, version: 3.8.4 }
      sdkman_defaults:
        java: 11.0.12-open
        maven: 3.8.4
    - nvm_node
    # - role: grzegorznowak.nvm_node
    #   become: true
    #   nvm_install_script_version: "0.39.2"
    #   nvm_node_version: "18.12.0"
    #   nvm_dir: "/home/{{ user }}/.nvm/"
    #   nvm_user_name: "{{ user }}"
    # - role: grzegorznowak.nvm_node
    #   nvm_dir: "/home/{{ user }}/.nvm/"
    #   nvm_user_name: "{{ user }}"
    #   nvm_node_version: "18.12.0"
    
