---
- hosts: localhost
  vars:
    user: dakon
  roles:
    - common
    - google-chrome
    - snap
    - vscode-extensions
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
              - command-not-found
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - zsh-completions
    - oh-my-zsh-plugins