---
- hosts: localhost
  vars:
    user: damico
    base:
    - htop
    - build-essential
    - net-tools
    - git
    - gitg
    - libfuse2
    - curl
    programs:
    - code
    programs_dev:
    - termius-app
    vscode_extensions:
    - vscode-icons-team.vscode-icons
    - ms-azuretools.vscode-docker
    - redhat.ansible
  roles:
    - common
    - google-chrome
    - snap
    - snap-dev
    - common-folder
    - vscode-extensions
    - role: geerlingguy.docker
      become: true
      docker_users:
        - "{{ user }}"
    - oh-my-zsh-plugins
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{ user }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
              - nvm
              - docker
              - command-not-found
              - zsh-syntax-highlighting
              - zsh-autosuggestions
              - zsh-completions
    - role: webarchitect609.jet_brains_toolbox
      become: true
      toolbox_version: "1.26.2.13244"
      toolbox_install_dir: "/home/{{ user }}/work/programs"
      toolbox_install_for_user: "{{ user }}"
    - role: comcast.sdkman
      sdkman_user: "{{ user }}"
      sdkman_group: "{{ user }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 11.0.12-open }
        - { candidate: maven, version: 3.8.4 }
      sdkman_defaults:
        java: 11.0.12-open
        maven: 3.8.4
    - nvm_node