---
- name: Git checkout
  ansible.builtin.git:
    repo: "{{ item.url }}"
    dest: "{{ folder }}/{{ item.name }}"
  loop: "{{ plugins }}"

- name: Install Spaceship
  include_tasks: spaceship-prompt
  when: spaceship.enabled